language: python
python:
  - "3.6"
addons:
  apt:
    packages:
    - openvpn
before_install:
  - sudo openvpn path/to/conf.ovpn &>>openvpn-client.log &
install:
  - npm install -g data-cli
  - pip install -r requirements.txt
script:
  - python co2-ppm-daily-flow.py
after_script:
  - data push